/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas.gui;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author UsEr
 */
public class UASGUI extends javax.swing.JFrame {
     
        Koneksi konek = new Koneksi();
        Connection con;

       
    public UASGUI() {
        initComponents();
         this.setTitle("BiodataSiswa");
        this.setLocationRelativeTo(this);
       
        konek.koneksi();
        this.statuskoneksi.setText(konek.statuskoneksi);
        table();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BiodataSiswa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inAlamat = new javax.swing.JTextField();
        inNama = new javax.swing.JTextField();
        inTempattanggallahir = new javax.swing.JTextField();
        inLakiLaki = new javax.swing.JRadioButton();
        inPerempuan = new javax.swing.JRadioButton();
        inAgama = new javax.swing.JComboBox<>();
        Selet = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        ww = new javax.swing.JLabel();
        statuskoneksi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbsiswa = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BiodataSiswa.setText("Biodata Siswa");

        jLabel2.setText("Agama");

        jLabel3.setText("JenisKelamin");

        jLabel4.setText("Tempat, tanggal lahir");

        jLabel5.setText("Alamat");

        jLabel6.setText("Nama");

        inLakiLaki.setText("LakiLaki");

        inPerempuan.setText("Petempuan");

        inAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Agama", "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Konghucu" }));

        Selet.setText("Reset");
        Selet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeletActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        ww.setText("Status Koneksi");

        statuskoneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statuskoneksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(BiodataSiswa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inLakiLaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inPerempuan))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inTempattanggallahir, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(inAlamat)
                                    .addComponent(inNama))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ww, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statuskoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Selet)
                                .addGap(38, 38, 38)
                                .addComponent(Update)
                                .addGap(50, 50, 50)
                                .addComponent(Delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(Simpan)))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(BiodataSiswa)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inTempattanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inLakiLaki)
                    .addComponent(inPerempuan))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(inAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Selet)
                    .addComponent(Update)
                    .addComponent(Delete)
                    .addComponent(Simpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ww)
                    .addComponent(statuskoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Biodata", jPanel1);

        tbsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "Tempattanggallahir", "Jeniskelamin", "Agama"
            }
        ));
        jScrollPane1.setViewportView(tbsiswa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tampil", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Statement pst ;
        ResultSet rs;

    public void table()
    {
    Koneksi konek = new Koneksi();
    konek.koneksi();
     try {
    String sql = "SELECT * from tbsiswa";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tbsiswa.setModel(DbUtils.resultSetToTableModel(rs));
        }
    catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void statuskoneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statuskoneksiActionPerformed
        // TODO add your handling code here:
         String JenisKelamin = "";
        if (inLakiLaki.isSelected()){
            JenisKelamin = "Laki-laki";
        }else if (inPerempuan.isSelected()){
            JenisKelamin = "Perempuan";
        }
      

        String Agama = ""; 
        if (inAgama.getSelectedIndex() == 1) {
            Agama = "Islam";
        } else if (inAgama.getSelectedIndex() == 2) {
            Agama = "Kristen";
        } else if (inAgama.getSelectedIndex() == 3) {
            Agama = "Katolik";
        } else if (inAgama.getSelectedIndex() == 4) {
            Agama = "Hindu";
        } else if (inAgama.getSelectedIndex() == 5) {
            Agama = "Budha";
        } else if (inAgama.getSelectedIndex() == 6) {
            Agama = "Konghucu";
        } else {
            return; 
        }
        
        String Nama = inNama.getText();
        String Alamat = inAlamat.getText();
        String TempatTanggalLahir = inTempattanggallahir.getText();
        Insert in = new Insert();
        in.insert(Nama, Alamat, TempatTanggalLahir, JenisKelamin, Agama);
        table();
    }//GEN-LAST:event_statuskoneksiActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
          String JenisKelamin = "";
        if (inLakiLaki.isSelected()){
            JenisKelamin = "Laki-laki";
        }else if (inPerempuan.isSelected()){
            JenisKelamin = "Perempuan";
        }
      

        String Agama = ""; 
        if (inAgama.getSelectedIndex() == 1) {
            Agama = "Islam";
        } else if (inAgama.getSelectedIndex() == 2) {
            Agama = "Kristen";
        } else if (inAgama.getSelectedIndex() == 3) {
            Agama = "Katolik";
        } else if (inAgama.getSelectedIndex() == 4) {
            Agama = "Hindu";
        } else if (inAgama.getSelectedIndex() == 5) {
            Agama = "Budha";
        } else if (inAgama.getSelectedIndex() == 6) {
            Agama = "Konghucu";
        } else {
            return; 
        }
        
        String Nama = inNama.getText();
        String Alamat = inAlamat.getText();
        String TempatTanggalLahir = inTempattanggallahir.getText();
        Insert in = new Insert();
        in.insert(Nama, Alamat, TempatTanggalLahir, JenisKelamin, Agama);
        table();
    }//GEN-LAST:event_SimpanActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        Koneksi konek = new Koneksi();
        konek.koneksi();
        Delete del = new Delete();
        del.delete(inNama.getText());
    
        table();
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
          Koneksi konek = new Koneksi();
        konek.koneksi();
        String JenisKelamin = "";
        if (inLakiLaki.isSelected()){
            JenisKelamin = "Laki-laki";
        }else if (inPerempuan.isSelected()){
            JenisKelamin = "Perempuan";
        }
      
         String Agama = ""; 
        if (inAgama.getSelectedIndex() == 1) {
            Agama = "Islam";
        } else if (inAgama.getSelectedIndex() == 2) {
            Agama = "Kristen";
        } else if (inAgama.getSelectedIndex() == 3) {
            Agama = "Katolik";
        } else if (inAgama.getSelectedIndex() == 4) {
            Agama = "Hindu";
        } else if (inAgama.getSelectedIndex() == 5) {
            Agama = "Budha";
        } else if (inAgama.getSelectedIndex() == 6) {
            Agama = "Konghucu";
        } else {
            return; 
        }
        String Nama= inNama.getText();
        String Alamat = inAlamat.getText();
        String TempatTanggalLahir = inTempattanggallahir.getText();

       Update update = new Update();
        update.Update(Nama, Alamat, TempatTanggalLahir, JenisKelamin, Agama);
        table();
    }//GEN-LAST:event_UpdateActionPerformed

    private void SeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeletActionPerformed
        // TODO add your handling code here:
        //getselectedIndex get index number of selected item:
      
        inNama.setText("");
        inLakiLaki.setSelected(false);
        inPerempuan.setSelected(false);
        inAlamat.setText("");
        inTempattanggallahir.setText("");
        inAgama.setSelectedIndex(0);

    }//GEN-LAST:event_SeletActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UASGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UASGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UASGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UASGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UASGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BiodataSiswa;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Selet;
    private javax.swing.JButton Simpan;
    private javax.swing.JButton Update;
    private javax.swing.JComboBox<String> inAgama;
    private javax.swing.JTextField inAlamat;
    private javax.swing.JRadioButton inLakiLaki;
    private javax.swing.JTextField inNama;
    private javax.swing.JRadioButton inPerempuan;
    private javax.swing.JTextField inTempattanggallahir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField statuskoneksi;
    private javax.swing.JTable tbsiswa;
    private javax.swing.JLabel ww;
    // End of variables declaration//GEN-END:variables
}
